Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 1500

Style/StringLiterals:
  EnforcedStyle: double_quotes
